### ISSUE TITLE
us.battle.net - missed share buttons

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExperimentalFilter#1028]
https://us.battle.net/support/en/article/error-3

**Comment by Alex-302** [comment]
That's because Adguard did not injected to the page.

**Comment by ameshkov** [comment]
elemhide?

**Comment by Alex-302** [comment]
nothing. no exclusions there. I see the different results in Chrome and Firefox.
In Chrome:
![-](http://imagizer.imageshack.com/img908/9497/Z0C5Iz.jpg)
in Firefox:
![-](http://imagizer.imageshack.com/img908/3794/93zzDy.jpg)

**Comment by ameshkov** [comment]
Please fill a bug report in Adguard for Windows project.

**Comment by Alex-302** [comment]
done

**Comment by ameshkov** [comment]
Still missing buttons in the article footer:
http://us.battle.net/d3/en/blog/19858618/season-4-now-live-8-28-2015

**Comment by Alex-302** [comment]
That's because no Adguard injections
See this issue
https://github.com/AdguardTeam/AdguardForWindows/issues/571

**Comment by Alex-302** [comment]
Closed here
